# Generated by Django 4.1.7 on 2023-03-24 13:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='decription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
