# Generated by Django 4.1.7 on 2023-03-24 13:38

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='decription',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
