# Generated by Django 4.1.7 on 2023-04-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_decription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category_name',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category_name',
            field=models.ManyToManyField(blank=True, null=True, to='blog.category'),
        ),
    ]
