# Generated by Django 4.1.7 on 2023-04-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpost_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='category_name',
            new_name='e',
        ),
    ]
