# Generated by Django 4.1.7 on 2023-04-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_category_name_blogpost_e'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='e',
            new_name='category_name',
        ),
    ]
