# Generated by Django 4.1.7 on 2023-04-13 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_e_blogpost_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category_name',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
