# Generated by Django 4.1.7 on 2023-04-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_blogpost_category_name_blogpost_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
