# Generated by Django 4.1.7 on 2023-04-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_homeslider_description_alter_homeslider_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
